"""add transaction table

Revision ID: 02acbb77c42c
Revises: 5e181739126a
Create Date: 2023-03-28 13:49:28.984587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02acbb77c42c'
down_revision = '5e181739126a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('user_ip', sa.String(), nullable=False),
    sa.Column('user_location', sa.String(), nullable=False),
    sa.Column('transaction_description', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transaction_transaction_amount'), 'transaction', ['transaction_amount'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_id'), 'transaction', ['transaction_id'], unique=True)
    op.add_column('account', sa.Column('account_balance', sa.Float(), nullable=True))
    op.alter_column('account', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('account', 'account_balance')
    op.drop_index(op.f('ix_transaction_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_transaction_amount'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
