"""create account table

Revision ID: 59b5b72c42bd
Revises: ab3699b5255e
Create Date: 2023-03-27 06:20:41.894237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b5b72c42bd'
down_revision = 'ab3699b5255e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_account_account_id'), 'account', ['account_id'], unique=True)
    op.create_index(op.f('ix_account_account_number'), 'account', ['account_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_account_number'), table_name='account')
    op.drop_index(op.f('ix_account_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
