"""updated relationship migration table

Revision ID: 5e181739126a
Revises: 59b5b72c42bd
Create Date: 2023-03-27 06:46:42.988538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e181739126a'
down_revision = '59b5b72c42bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_account_number', table_name='account')
    op.create_index(op.f('ix_account_account_number'), 'account', ['account_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_account_number'), table_name='account')
    op.create_index('ix_account_account_number', 'account', ['account_number'], unique=False)
    # ### end Alembic commands ###
